[profile.default]
optimizer_runs = 10000
src = 'contracts'
fs_permissions = [{ access = "read", path = "./deployments/"}]

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
goerli = {key = "${ETHERSCAN_API_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_API_KEY}"}