name: Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  forge-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Restore cached node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./packages/node_modules
          key: ${{ runner.os }}-${{ steps.nvm.outputs.NVMRC }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.nvm.outputs.NVMRC }}-nodemodules-

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install JS dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install --frozen-lockfile --prefer-offline

      - name: Build contract
        run: forge build

      - name: Check gas snapshots
        env:
          RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}
        run: forge snapshot --check

      - name: Run tests
        env:
          RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}
        run: forge test --force --optimize -vvv
